/**
 * Right-side artifact panel — the WorkBuddy-style split-pane sidebar
 * shown next to the Chat conversation.  Hosts four tabs:
 *
 *   - 变更 (changes): list of files written/edited in the conversation,
 *     click → file detail (source / preview / diff / info, editable when
 *     the file lives in a writable sandbox root).
 *   - 全部文件 (allFiles): placeholder, "敬请期待".
 *   - 浏览器 (browser): read-only workspace tree + file preview, scoped
 *     to the current agent's `agent.workspace`.
 *   - 产物 (artifacts): placeholder, "敬请期待".
 *
 * Open/close + tab + focused-file state lives in the
 * `useArtifactPanel` zustand store so any part of the page (file cards,
 * toolbar buttons, "查看文件变更 →" links) can drive it.
 */
import { useEffect, useMemo } from 'react';
import { ArrowLeft, FileEdit, Files, FolderTree, Package, X } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import type { GeneratedFile } from '@/lib/generated-files';
import type { AgentSummary } from '@/types/agent';
import { useArtifactPanel } from '@/stores/artifact-panel';
import type { FilePreviewTarget } from './types';
import { FilePreviewBody } from './FilePreviewBody';
import { FilePreviewIcon } from './file-card-utils';
import { WorkspaceBrowserBody } from './WorkspaceBrowserBody';

export interface ArtifactPanelProps {
  /** All files generated by the AI across the conversation. */
  files: GeneratedFile[];
  /** Currently selected agent (drives the workspace tab). */
  agent: AgentSummary | null;
  /** Used to mark "本轮新增" badges on the workspace tree. */
  runStartedAt?: number | null;
  /** Bumping this number triggers a workspace tree reload. */
  refreshSignal?: number;
}

export function ArtifactPanel({ files, agent, runStartedAt, refreshSignal }: ArtifactPanelProps) {
  const { t } = useTranslation('chat');
  const tab = useArtifactPanel((s) => s.tab);
  const setTab = useArtifactPanel((s) => s.setTab);
  const focusedFile = useArtifactPanel((s) => s.focusedFile);
  const setFocusedFile = useArtifactPanel((s) => s.setFocusedFile);
  const close = useArtifactPanel((s) => s.close);

  return (
    <div className="flex h-full min-h-0 flex-col bg-background">
      <div className="flex shrink-0 items-center justify-between gap-2 border-b border-black/5 px-3 py-2 dark:border-white/10">
        <div className="flex min-w-0 items-center gap-1">
          <PanelTabButton
            icon={<FileEdit className="h-3.5 w-3.5" />}
            label={t('artifactPanel.tabs.changes', '变更')}
            active={tab === 'changes'}
            onClick={() => setTab('changes')}
          />
          <PanelTabButton
            icon={<Files className="h-3.5 w-3.5" />}
            label={t('artifactPanel.tabs.allFiles', '全部文件')}
            active={tab === 'allFiles'}
            onClick={() => setTab('allFiles')}
          />
          <PanelTabButton
            icon={<FolderTree className="h-3.5 w-3.5" />}
            label={t('artifactPanel.tabs.browser', '浏览器')}
            active={tab === 'browser'}
            onClick={() => setTab('browser')}
          />
          <PanelTabButton
            icon={<Package className="h-3.5 w-3.5" />}
            label={t('artifactPanel.tabs.artifacts', '产物')}
            active={tab === 'artifacts'}
            onClick={() => setTab('artifacts')}
          />
        </div>
        <Button
          type="button"
          variant="ghost"
          size="icon"
          className="h-7 w-7 shrink-0"
          onClick={close}
          aria-label={t('filePreview.actions.close', '关闭')}
        >
          <X className="h-4 w-4 pointer-events-none" />
        </Button>
      </div>

      <div className="min-h-0 flex-1">
        {tab === 'changes' && (
          <ChangesTab
            files={files}
            focusedFile={focusedFile}
            onFocus={(f) => setFocusedFile(f)}
            onBack={() => setFocusedFile(null)}
          />
        )}
        {tab === 'browser' && (
          <WorkspaceBrowserBody
            agent={agent}
            runStartedAt={runStartedAt}
            refreshSignal={refreshSignal}
            compact
          />
        )}
        {tab === 'allFiles' && <PlaceholderTab tab="allFiles" />}
        {tab === 'artifacts' && <PlaceholderTab tab="artifacts" />}
      </div>
    </div>
  );
}

interface PanelTabButtonProps {
  icon: React.ReactNode;
  label: string;
  active: boolean;
  onClick: () => void;
}

function PanelTabButton({ icon, label, active, onClick }: PanelTabButtonProps) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        'flex items-center gap-1.5 rounded-md px-2.5 py-1 text-xs font-medium transition-colors',
        active
          ? 'bg-foreground/10 text-foreground'
          : 'text-muted-foreground hover:bg-black/5 hover:text-foreground dark:hover:bg-white/10',
      )}
    >
      {icon}
      <span>{label}</span>
    </button>
  );
}

function PlaceholderTab({ tab }: { tab: 'allFiles' | 'artifacts' }) {
  const { t } = useTranslation('chat');
  return (
    <div className="flex h-full flex-col items-center justify-center gap-2 px-6 text-center">
      <p className="text-sm font-medium text-foreground/70">
        {tab === 'allFiles'
          ? t('artifactPanel.tabs.allFiles', '全部文件')
          : t('artifactPanel.tabs.artifacts', '产物')}
      </p>
      <p className="max-w-xs text-xs text-muted-foreground">
        {t('artifactPanel.comingSoon', '敬请期待')}
      </p>
    </div>
  );
}

interface ChangesTabProps {
  files: GeneratedFile[];
  focusedFile: FilePreviewTarget | null;
  onFocus: (file: FilePreviewTarget) => void;
  onBack: () => void;
}

function generatedFileToTarget(file: GeneratedFile): FilePreviewTarget {
  return {
    filePath: file.filePath,
    fileName: file.fileName,
    ext: file.ext,
    mimeType: file.mimeType,
    contentType: file.contentType,
    fullContent: file.fullContent,
    edits: file.edits,
  };
}

function ChangesTab({ files, focusedFile, onFocus, onBack }: ChangesTabProps) {
  const { t } = useTranslation('chat');

  // De-dup files by path, keep the latest entry (highest lastSeenIndex).
  const uniqueFiles = useMemo(() => {
    const map = new Map<string, GeneratedFile>();
    for (const f of files) {
      const existing = map.get(f.filePath);
      if (!existing || f.lastSeenIndex >= existing.lastSeenIndex) map.set(f.filePath, f);
    }
    return Array.from(map.values()).sort((a, b) => b.lastSeenIndex - a.lastSeenIndex);
  }, [files]);

  // If the focused file disappears from the list (rare — chat reset?),
  // pop back to the list view automatically.
  useEffect(() => {
    if (!focusedFile) return;
    const stillExists = uniqueFiles.some((f) => f.filePath === focusedFile.filePath);
    if (!stillExists) onBack();
  }, [focusedFile, uniqueFiles, onBack]);

  if (focusedFile) {
    return (
      <FilePreviewBody
        file={focusedFile}
        compact
        leadingHeader={
          <Button
            type="button"
            variant="ghost"
            size="icon"
            className="h-7 w-7"
            onClick={onBack}
            aria-label={t('artifactPanel.actions.back', '返回列表')}
            title={t('artifactPanel.actions.back', '返回列表')}
          >
            <ArrowLeft className="h-4 w-4 pointer-events-none" />
          </Button>
        }
      />
    );
  }

  if (uniqueFiles.length === 0) {
    return (
      <div className="flex h-full items-center justify-center px-6 text-center text-sm text-muted-foreground">
        {t('artifactPanel.changes.empty', '本会话尚无文件变更')}
      </div>
    );
  }

  return (
    <div className="h-full overflow-y-auto px-3 py-3">
      <div className="mb-2 flex items-center justify-between px-1">
        <p className="text-xs font-semibold text-foreground/80">
          {t('artifactPanel.changes.heading', { count: uniqueFiles.length, defaultValue: '文件变更（{{count}} 个）' })}
        </p>
      </div>
      <ul className="space-y-1">
        {uniqueFiles.map((file) => {
          const editCount = file.edits?.length ?? 0;
          return (
            <li key={file.filePath}>
              <button
                type="button"
                onClick={() => onFocus(generatedFileToTarget(file))}
                className={cn(
                  'group flex w-full items-center gap-2 rounded-lg border border-transparent px-2 py-2 text-left transition-colors',
                  'hover:border-black/10 hover:bg-black/[0.03] dark:hover:border-white/10 dark:hover:bg-white/5',
                )}
                title={file.filePath}
              >
                <FilePreviewIcon
                  contentType={file.contentType}
                  mimeType={file.mimeType}
                  ext={file.ext}
                  className="h-4 w-4 shrink-0 text-muted-foreground"
                />
                <div className="min-w-0 flex-1">
                  <p className="truncate text-xs font-medium text-foreground">{file.fileName}</p>
                  <p className="truncate text-2xs text-muted-foreground">{file.filePath}</p>
                </div>
                <div className="flex shrink-0 items-center gap-1.5">
                  <Badge
                    variant={file.action === 'created' ? 'default' : 'secondary'}
                    className="text-2xs px-1.5 py-0"
                  >
                    {file.action === 'created'
                      ? t('generatedFiles.created', '新增')
                      : t('generatedFiles.modified', '修改')}
                  </Badge>
                  {editCount > 0 && (
                    <span className="text-2xs font-mono text-muted-foreground">×{editCount}</span>
                  )}
                </div>
              </button>
            </li>
          );
        })}
      </ul>
    </div>
  );
}

export default ArtifactPanel;
